### ISSUE TITLE
[speech-to-text] System.Net.Http conflict

### ISSUE THREAD

**Issue by Jamie22** [watson-developer-cloud/dotnet-standard-sdk#118] opened 2017-06-21 20:38 UTC
When I build my project, I get the following warning:

> Severity	Code	Description	Project	File	Line	Suppression State
Warning	MSB3243	No way to resolve conflict between "System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Net.Http, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Choosing "System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" arbitrarily.	SliqSpeechToTextCore	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets	1964	

When I run, I get this exception when I try to instantiate the service by calling new SpeechToTextService()

> **System.IO.FileLoadException:** 'Could not load file or assembly 'System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

My csproj is

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.1</TargetFramework>
    <PackageTargetFallback>dnxcore50;portable-net45+netcore45+wp8+wp81+wpa81;</PackageTargetFallback>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IBM.WatsonDeveloperCloud.SpeechToText.v1" Version="1.0.0" />
  </ItemGroup>
  
</Project>

```

I tried installing System.Net.Http from NuGet but it didn't help.

**Comment by atilatosta** [comment] 2017-06-28 17:26
@Jamie22 soon will be available a new version, [see here (1.1.0)](https://github.com/watson-developer-cloud/dotnet-standard-sdk/milestone/3), that will fix this problem.

**Comment by OzTenBearAnt** [comment] 2017-07-07 16:14
I have IBM.WatsonDeveloperCloud 1.1.0 installed with a project targeting .NET 4.6.1 but still get a related error with SpeechToText().

> [FileLoadException: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)]
   System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +0
   System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +36
   System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks) +152
   System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection) +77
   System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection) +21
   System.Reflection.Assembly.Load(String assemblyString) +28
   System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective) +38

Looking at NuGet the most recent version you've released of System.Net.Http.Formatting is 5.2.3, yet this seems to be referencing 5.2.4. 

My csproj:
`    <Reference Include="System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>..\packages\System.Net.Http.4.3.1\lib\net46\System.Net.Http.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http.Formatting, Version=5.2.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
      <HintPath>..\packages\Wdc.System.Net.Http.Formatting.NetStandard.1.0.0\lib\netstandard1.1\System.Net.Http.Formatting.dll</HintPath>
    </Reference>`

My web.config:
`      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.1.1.0" newVersion="4.1.1.0" />
      </dependentAssembly>
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http.Formatting" publicKeyToken="31bf3856ad364e35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.4.0" newVersion="5.2.4.0" />
      </dependentAssembly>`

I have System.Net.Http 4.3.1 installed and have tried adjusting the binding redirects to reflect this but that did not solve the issue either.

Should this issue be reopened or a new one created?

**Comment by atilatosta** [comment] 2017-07-07 17:03
@OzTenBearAnt Please, have you tried installing the Wdc.System.Net.Http.Formatting.NetStandard package?

**Comment by OzTenBearAnt** [comment] 2017-07-07 17:34
@atilatosta Yes I have version 1.0.0 of Wdc.System.Net.Http.Formatting.NetStandard installed. This is what seems to be incorrectly referencing System.Net.Http.Formatting version 5.2.**4** which does not exist.

**Comment by atilatosta** [comment] 2017-07-07 17:47
@OzTenBearAnt weird! I just created a repository with an example running 4.6.1 and STT. Please make sure it works on your machine.
[wdc-stt-example](https://github.com/atilatosta/wdc-stt-example)

**Comment by OzTenBearAnt** [comment] 2017-07-07 18:04
@atilatosta I downloaded your repo and setup the solution with my own wdc username and password in VS2017. I get the same exact runtime error when initializing SpeechToTextService

> System.IO.FileLoadException occurred
  HResult=0x8013141A
  Message=Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
  Source=IBM.WatsonDeveloperCloud
  StackTrace:
   at IBM.WatsonDeveloperCloud.Http.WatsonHttpClient..ctor(String baseUri, String userName, String password)
   at IBM.WatsonDeveloperCloud.Service.WatsonService..ctor(String serviceName, String url)
   at IBM.WatsonDeveloperCloud.SpeechToText.v1.SpeechToTextService..ctor()
   at IBM.WatsonDeveloperCloud.SpeechToText.v1.SpeechToTextService..ctor(String userName, String password)

**Comment by atilatosta** [comment] 2017-07-07 18:49
@OzTenBearAnt the version 5.2.4 has not yet been released by Microsoft, though we recompiled it to the .net standard library and added the package to nuget.org [Wdc.System.Net.Http.Formatting.NetStandard](https://www.nuget.org/packages/Wdc.System.Net.Http.Formatting.NetStandard/). So dotnet-standard-sdk version 1.1.0 is referencing this package. Please, have you tried clearing your nuget's cache or doing the restore?

**Comment by OzTenBearAnt** [comment] 2017-07-07 21:56
@atilatosta I did clear the cache and I have VS setup to restore packages automatically, still getting the same error. I've unloaded and reloaded the project, cleaned and rebuilt the solution, etc. Definitely still something wrong here.

**Comment by atilatosta** [comment] 2017-07-07 22:15
@OzTenBearAnt sorry! on my machine is happening okay, there is a guy on my team who has been able to reproduce the same error as you, I am trying to identify what is happening.

**Comment by ratans** [comment] 2017-07-11 16:28
Any timeline on when we can expect this to be resolved. Its holding all our development work related to natural language understanding api.

**Comment by ratans** [comment] 2017-07-11 18:13
We are really waiting for this to work, please let us know what is the status/timeline. Is there a way I can use your service by making REST api service calls without using SDK for the time. Any sample demo/link would be helpful. Thanks.

**Comment by mediumTaj** [comment] 2017-07-11 18:54
@atilatosta is working on it. For some reason he cannot reproduce on his local machine. We will release an update as soon as we find a solution.

**Comment by atilatosta** [comment] 2017-07-11 20:01
@ratans hey guys! we are actively working on it. I believe I'm having problems signing the assembly. I soon hope to solve.

**Comment by yaxv** [comment] 2017-07-13 11:54
Not sure if this is a usable workaround but at least the following steps seemed to make the .NET framework stop from throwing the following exception:

> System.IO.FileLoadException occurred
>   HResult=0x8013141A
>   Message=Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
>   Source=IBM.WatsonDeveloperCloud

I found this article which suggests how validation can be disabled for a particular assembly:

Strong name validation failed. (Exception from HRESULT: 0x8013141A) – Anything And Everything by Keith McGuinness
https://blogs.msdn.microsoft.com/keithmg/2012/03/20/strong-name-validation-failed-exception-from-hresult-0x8013141a/

I made a registry file exactly as described in the article, naturally with the PublicKeyToken for System.Net.Http.Formatting as such:

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\StrongName\Verification\*,31bf3856ad364e35]
[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\StrongName\Verification\*,31bf3856ad364e35]
```

I saved the file as DisableSystemNetHttpFormatting.reg. You can always create a EnableSystemNetHttpFormatting.reg as such:

```
Windows Registry Editor Version 5.00

[-HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\StrongName\Verification\*,31bf3856ad364e35]
[-HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\StrongName\Verification\*,31bf3856ad364e35]
```

**Comment by mediumTaj** [comment] 2017-07-13 14:23
@ratans can you try @yaxv workaround to see if will work for you until @atilatosta solves the issue?

**Comment by ratans** [comment] 2017-07-13 20:03
@mediumTaj - Thanks for the update. I will try using this fix. But I got a work around that was holding up everything. So I am fine waiting for the updated build from the team on this.

**Comment by enginates** [comment] 2017-08-16 16:31
i have tried that reg , but still getting error, seems VS2015 does not check the reg for that

**Comment by yaxv** [comment] 2017-08-17 15:49
@enginates I'm afraid you're right. I also get the error message when running the code in VS2015. It solves the problem in VS2017 / Windows 10 though.

**Comment by vyarovoy** [comment] 2017-08-27 19:21
@atilatosta how it's going with subject issue? 
We have a thirst in our project to start using IBM NLU capabilities via SDK but discovered we are simply blocked by this ticket.

**Comment by atilatosta** [comment] 2017-08-28 18:27
@vyarovoy Did you install the dependency [Wdc.System.Net.Http.Formatting.NetStandard](https://www.nuget.org/packages/Wdc.System.Net.Http.Formatting.NetStandard/)? What error exactly are you getting?

**Comment by vyarovoy** [comment] 2017-08-28 19:43
@atilatosta given very basic example - console app targeting .NET Framework 4.6, IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1 added via nuget. I see IBM.WatsonDeveloperCloud (>= 1.1.0) as its dependency and Wdc.System.Net.Http.Formatting.NetStandard (>= 1.0.0) as cascading dependency from last one.

As a result I see Wdc.System.Net.Http.Formatting.NetStandard v1.0.7 installed as dependency to my console app.

At very 1st line of [tutorial](https://github.com/watson-developer-cloud/dotnet-standard-sdk/tree/development/src/IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1) 

`NaturalLanguageUnderstandingService _naturalLanguageUnderstandingService = new NaturalLanguageUnderstandingService();`

I got exception 
An unhandled exception of type 'System.IO.FileLoadException' occurred in IBM.WatsonDeveloperCloud.dll

Additional information: Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)

**Comment by ratans** [comment] 2017-09-01 09:47
@atilatosta  - Any idea when we can expect a fix for this. This is a showstopper bug for us going forward, and migrating our application from old service to new one.

**Comment by vyarovoy** [comment] 2017-09-05 05:17
@atilatosta , @ratans yesterday I run over my demo project by luck and found bunch of nuget packages updates pending. Right after update process issue mentioned above has gone, service instance now initializes without any error.

My colleague said there is another tricky error further way but seems as it will be separate topic.

**Comment by atilatosta** [comment] 2017-09-05 17:12
@vyarovoy good! Tks!

@ratans i'm having difficulty generating the scenario, in my machine it works. Let me know more details about your environment

**Comment by ratans** [comment] 2017-09-13 19:37
@atilatosta I tried to create another sample today, and faced the same issue.

Steps to reproduce 
----------------------
Environment - Windows 10, VS 2017

Create a new console app, and add nuget package using :
PM > Install-Package IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1

Next add this one line of code, and you get below error.

`NaturalLanguageUnderstandingService _naturalLanguageUnderstandingService = new NaturalLanguageUnderstandingService();
`
**Error**

System.IO.FileLoadException occurred
  HResult=0x8013141A
  Message=Could not load file or assembly 'System.Net.Http.Formatting, Version=5.2.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
  Source=IBM.WatsonDeveloperCloud
  StackTrace:
   at IBM.WatsonDeveloperCloud.Http.WatsonHttpClient..ctor(String baseUri, String userName, String password)
   at IBM.WatsonDeveloperCloud.Service.WatsonService..ctor(String serviceName, String url)
   at IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1.NaturalLanguageUnderstandingService..ctor()
   at NewAlchemyDemo.Program.Main(String[] args) in E:\Demo\NewAlchemyDemo\NewAlchemyDemo\Program.cs:line 15

Inner Exception 1:
SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)

**Comment by cchen028** [comment] 2017-09-20 21:44
I'm getting the exact issue mentioned above. Wdc.System.Net.Http.Formatting.NetStandard did not resolve it for me. I'm also on Visual Studio 2017/Win 10

**Comment by yingkeen** [comment] 2017-09-21 16:15
Try to check the nuget package and update everything or update at least System.Net.Http.Formatting. It solve the issue for me. Similar to what @vyarovoy  did.

**Comment by ratans** [comment] 2017-09-22 16:33
I did update the version, and here is a new error I am facing now while executing below line 👍 

`NaturalLanguageUnderstandingService _naturalLanguageUnderstandingService = new NaturalLanguageUnderstandingService();`


System.Security.VerificationException occurred
  HResult=0x8013150D
  Message=Method System.Net.Http.CloneableExtensions.Clone: type argument 'System.Net.Http.Headers.MediaTypeHeaderValue' violates the constraint of type parameter 'T'.
  Source=System.Net.Http.Formatting
  StackTrace:
   at System.Net.Http.Formatting.MediaTypeConstants.get_ApplicationJsonMediaType()
   at System.Net.Http.Formatting.JsonMediaTypeFormatter..ctor()
   at System.Net.Http.Formatting.MediaTypeFormatterCollection.CreateDefaultFormatters()
   at IBM.WatsonDeveloperCloud.Http.WatsonHttpClient..ctor(String baseUri, String userName, String password)
   at IBM.WatsonDeveloperCloud.Service.WatsonService..ctor(String serviceName, String url)
   at IBM.WatsonDeveloperCloud.NaturalLanguageUnderstanding.v1.NaturalLanguageUnderstandingService..ctor()
   at NewAlchemyDemo.Program.Main(String[] args) in E:\Demo\NewAlchemyDemo\NewAlchemyDemo\Program.cs:line 15

**Comment by danhphan1307** [comment] 2017-09-30 05:05
In my case, I also had to change web.config. It must be declared 5.2.4.0 as below
      <dependentAssembly>
        <assemblyIdentity name="System.Net.Http.Formatting" publicKeyToken="31BF3856AD364E35" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-5.2.4.0" newVersion="5.2.4.0" />
      </dependentAssembly>

**Comment by ynazami** [comment] 2017-10-15 17:19
Any updates on this issue, we are evaluating a platform and are hitting this error in the POC. Seems like this is active for more than 5 months and still not resolved :( We are facing same error in Conversation SDK for .Net.

**Comment by xjose97x** [comment] 2017-10-26 13:01
I get this issue when instantiating the ConversationService. 

Is there a fix for this yet? Perhaps a workaround? Have been researching a bit, and seems like this is a common issue when working with .NET Standard and normal .NET Framework. .NET Core does not have this issue when working with .NET Standard.

Perhaps could be worth it to rewrite this library in .NET Framework? Shouldn't be hard since is the same code.

@atilatosta

**Comment by ratans** [comment] 2017-10-26 17:58
I am really worried the way it is getting delayed to release a fix for this. 

We are waiting to move our application to use the new bluemix code, from the obsolete alchemyapi token based approach. But this issue is not letting us move ahead.

Anyone from the team, can you guys give us a realistic timeline on this fix.

For any details on the issue I am facing, please check above comments.

**Comment by xjose97x** [comment] 2017-10-26 18:46
@ratans , as for now, I copied this code into a .NET Framework code. The only issue here is that you won't have this as a NuGet package, but instead a project inside your solution.

**Comment by yaseminaladi** [comment] 2017-11-02 14:44
xjose97x can you give more detail please?

**Comment by AnjuAlphonsa** [comment] 2018-01-18 06:27
I want to know about the '[speech-to-text] System.Net.Http conflict #118' issue solved or not? if solved give me the solution.. plz..

**Comment by AnjuAlphonsa** [comment] 2018-01-18 12:21
I want to know about the [speech-to-text] System.Net.Http conflict #118 issue solved or not? if solved give me the solution... Plzz...

**Comment by ratans** [comment] 2018-01-18 20:41
I see a latest version is added , but I am still facing the same issue with  System.Net.Http

Can someone verify if it is working for any version of DotNet

**Comment by mediumTaj** [comment] 2018-01-22 20:00
@atilatosta is still trying to find some time to look into this.

**Comment by dasiths** [comment] 2018-02-01 03:43
Any update on this?

**Comment by AnjuAlphonsa** [comment] 2018-02-01 04:13
Finally I solved this problem by
1. installing Wdc.System.Net.Http.Formatting.NetStandard  nuget package
2. downgrade System.Net.Http version 4.1.0 to 4.0.0

This worked for me..

**Comment by themisterbondy** [comment] 2018-02-28 21:33
@AnjuAlphonsa 
**_Thank you, this worked for me!_**

**Comment by ratans** [comment] 2018-03-14 18:46
Just wanted to give an update. It worked for me when I am installing this in an Asp.Net Core application.

**Comment by xjose97x** [comment] 2018-03-15 14:18
@ratans ya, this issue only appeared when working in a .net framework application.

**Comment by fmarsland** [comment] 2018-05-04 18:28
Wondering if this issue was ever fixed? I am encountering this problem trying to use the natural language understanding, and losing my mind trying to get this to work. Tried the suggested workarounds/fixes, but I am working in a framework application, so I suspect I may be sol.

**Comment by mediumTaj** [comment] 2018-05-04 20:38
@fmarsland Can you please try installing 

```
Wdc.System.Net.Http.Formatting.NetStandard 1.0.7
System.Net.Http 4.3.1
```

**Comment by sumitrathee** [comment] 2018-06-25 06:34
This information might help someone. I was receiving this exception while instantiating SpeechToTextService class. - System.Security.VerificationException: 'Method System.Net.Http.CloneableExtensions.Clone: type argument 'System.Net.Http.Headers.MediaTypeHeaderValue' violates the constraint of type parameter 'T'.'

Resolution - Updating System.Net.Http nuget version to 4.3.3 resolved the issue for me.

**Comment by mediumTaj** [comment] 2019-07-19 20:13
Is this still an issue?

**Comment by mediumTaj** [comment] 2019-10-04 21:35
Closing due to inactivity. Please reopen if this is still an issue.

**Closed by mediumTaj** 2019-10-04 21:35 UTC
Labels: bug, high-priority
