### ISSUE TITLE
[Speech-To-Text] Throws with "bad request" when requesting timestamps for recognize call

### ISSUE THREAD

**Issue by qunliu** [watson-developer-cloud/dotnet-standard-sdk#270] opened 2018-07-27 11:49 UTC
I have a lite account and try some simple code to see if it works for me. It works with a simple call, but as long as I add metadata to request timestamps, it'd throw. Any clue? Here is my code:

```
public void Recognize( string wavFileName )
 {
         TokenOptions tokenOptions = new TokenOptions()
         {
            ServiceUrl = "https://gateway-wdc.watsonplatform.net/speech-to-text/api",  // service url for US East
            IamApiKey = "myapikey"
         };
         var service = new SpeechToTextService( tokenOptions );
         SpeechRecognitionResults response = null;
         using ( var fs = File.OpenRead( wavFileName ) )
         {
            Metadata m = new Metadata
            {
               Timestamps = true
            };
            response = service.Recognize( "audio/wav", m, fs ); // throws with "bad request"
            //response = service.Recognize( "audio/wav", fs ); // This works fine
         }

         Console.WriteLine( "Recognize() succeeded:\n{0}", JsonConvert.SerializeObject( response, Formatting.Indented ) ); 
}
```

I am running this on Windows 10. Thanks!

**Comment by mediumTaj** [comment] 2018-07-27 14:24
Looking at this still - closing as it's a duplicate of https://github.com/watson-developer-cloud/dotnet-standard-sdk/issues/198

**Closed by mediumTaj** 2018-07-27 14:24 UTC
Labels: duplicate

**Comment by mediumTaj** [comment] 2018-07-27 16:31
Right now I'm trying to investigate the best way to do this. We currently have a generated method `RecognizeSessionless()` but it accepts a bytearray. 

https://github.com/watson-developer-cloud/dotnet-standard-sdk/blob/development/src/IBM.WatsonDeveloperCloud.SpeechToText.v1/SpeechToTextService.cs#L290

I'll need to revise the handwritten method though.

**Comment by mediumTaj** [comment] 2018-07-27 16:50
Actually I just tried this and it looks like it works. Add timestamps in the params rather than in metadata. The service may have deprecated this and the change was not picked up. Can you confirm?
```
SpeechRecognitionResults recognizeResults;
using (var fs = File.OpenRead(_acousticResourcePath))
{
    recognizeResults = service.Recognize("audio/wav", fs, timestamps: true);
}
```

**Comment by qunliu** [comment] 2018-07-27 17:01
> Actually I just tried this and it looks like it works. Add timestamps in the params rather than in metadata. The service may have deprecated this and the change was not picked up. Can you confirm?

It does work this way, thanks, I appreciate your help!
