### ISSUE TITLE
[translator] Implement async methods

### ISSUE THREAD

**Issue by mstama** [watson-developer-cloud/dotnet-standard-sdk#146] opened 2017-08-18 14:09 UTC
All the methods implemented by the translator service are not async but use the IClient interface that uses async methods.
All the requests are then made with an async IClient with the ".Result" at the end turning an async request into a sync request.
So just expose the methods as async and use the async httpClient methods as async methods.

**Comment by mediumTaj** [comment] 2019-07-19 20:14
Closing as duplicate of https://github.com/watson-developer-cloud/dotnet-standard-sdk/issues/262

**Closed by mediumTaj** 2019-07-19 20:14 UTC
Labels: low-priority
